spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
<<<<<<< HEAD
      username: root
      password: ********
=======
      username: *****
      password: ******
>>>>>>> bba104ca8d982df81bcc1eebc3f3ac80aac1b0c0
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小
      initial-size: 5
      # 最小空闲数
      min-idle: 5
      # 最大活动数量
      max-active: 30
      # 最大等待时间
      max-wait: 6000

  redis:
    database: 0
    host: localhost
    port: 6379
<<<<<<< HEAD
=======
    password: *****
>>>>>>> bba104ca8d982df81bcc1eebc3f3ac80aac1b0c0

    jedis:
      pool:
        max-active: 30
        max-wait: 1000
        max-idle: 10
        min-idle: 5
    timeout: 6000
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: 1459676432@qq.com
    password: ****************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


# 发送邮件配置
mail:
  from-mail:
    addr: 某不知名博客<1459676432@qq.com>
  verify-code:
    title: 【某博客验证码】
    content: 【验证码】


mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    root: info
    org:
      springframework: info

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  default-count: 10

# 因为太贵了，所以用不起
# 阿里云 oss储存服务
#aliyun:
#  oss:
#    address: your oss address
#    end-point: oss-cn-shenzhen.aliyuncs.com
#    access-key: your access key
#    secret-key: you secret key
#    bucket: your bucket name
# 直接将文件上传到服务器的储存路径
#file-upload:
#  image-path: /www/wwwroot/blog-res/image/
qiniu:
<<<<<<< HEAD
    access-key: *******************
    secret-key: *******************
    bucket: *****
    link-pre: http://pic.jratil.co/
=======
    access-key: ***********************
    secret-key: ***********************
    bucket: *****
    link-pre: ***************
server:
  port: 8866
>>>>>>> bba104ca8d982df81bcc1eebc3f3ac80aac1b0c0
